name: "Docker vulnerability scan"
description: "Scan docker containers for vulnerabilities"

inputs:
  docker_image:
    description: "The docker image and tag to be scanned"
    required: true
  dockerfile_path:
    description: "The path to the Dockerfile being scanned"
    required: true
  platform:
    description: "The Docker image platform that's being scanned"
    required: false
    default: "linux/amd64"
  token:
    description: "Token for allowing the action to post in the security tab"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run docker vulnerability scanner
      uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # v0.34.0
      env:
        TRIVY_PLATFORM: ${{ inputs.platform }}
      with:
        image-ref: "${{ inputs.docker_image }}"
        format: "sarif"
        scanners: "vuln"
        vuln-type: "os"
        timeout: "15m"
        output: "trivy-results.sarif"

    - name: Update sarif vulnerability locations
      run: |
        cat trivy-results.sarif | \
          jq '.runs[].results[].locations[].physicalLocation.artifactLocation += {"uri": "${{ inputs.dockerfile_path }}","uriBaseId": "ROOTPATH"}' | \
          jq '.runs[].results[].locations[].physicalLocation.region += {"startLine": 1,"startColumn": 1,"endLine": 1,"endColumn": 1}' | \
          jq '.runs[].results[] |= (if .ruleId then . + {partialFingerprints: {"primaryLocationLineHash": .ruleId}} else . end)' > sarif.tmp
        mv sarif.tmp trivy-results.sarif
      shell: bash

    - name: Upload trivy scan results to github security tab
      uses: github/codeql-action/upload-sarif@4355270be187e1b672a7a1c7c7bae5afdc1ab94a # v3.24.10
      with:
        sarif_file: "trivy-results.sarif"
        token: ${{ inputs.token }}
