name: "Docker vulnerability scan"
description: "Scan docker containers for vulnerabilities"

inputs:
  docker_image:
    description: "The docker image and tag to be scanned"
    required: true
  dockerfile_path:
    description: "The path to the Dockerfile being scanned"
    required: true
  platform:
    description: "The Docker image platform that's being scanned"
    required: false
    default: "linux/amd64"
  vuln_type:
    description: "The type of vulnerabilities to scan for (os, library)"
    required: false
    default: "os"
  token:
    description: "Token for allowing the action to post in the security tab"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Trivy
      env:
        TRIVY_VERSION: "0.69.3"
        TRIVY_SHA256_AMD64: "1816b632dfe529869c740c0913e36bd1629cb7688bd5634f4a858c1d57c88b75"
        TRIVY_SHA256_ARM64: "7e3924a974e912e57b4a99f65ece7931f8079584dae12eb7845024f97087bdfd"
      run: |
        bash "${{ github.action_path }}/../../scripts/install_trivy.sh" \
          "${{ env.TRIVY_VERSION }}" \
          "${{ env.TRIVY_SHA256_AMD64 }}" \
          "${{ env.TRIVY_SHA256_ARM64 }}"
      shell: bash

    - name: Trivy scan
      run: |
        trivy image \
          --format sarif \
          --platform ${{ inputs.platform }} \
          --vuln-type ${{ inputs.vuln_type }} \
          --security-checks vuln \
          --timeout 15m \
          --output trivy-results.sarif \
          ${{ inputs.docker_image }}
      shell: bash

    - name: Update sarif vulnerability locations
      run: |
        cat trivy-results.sarif | \
          jq '.runs[].results[].locations[].physicalLocation.artifactLocation += {"uri": "${{ inputs.dockerfile_path }}","uriBaseId": "ROOTPATH"}' | \
          jq '.runs[].results[].locations[].physicalLocation.region += {"startLine": 1,"startColumn": 1,"endLine": 1,"endColumn": 1}' | \
          jq '.runs[].results[] |= (if .ruleId then . + {partialFingerprints: {"primaryLocationLineHash": .ruleId}} else . end)' > sarif.tmp
        mv sarif.tmp trivy-results.sarif
      shell: bash

    - name: Upload trivy scan results to github security tab
      uses: github/codeql-action/upload-sarif@4355270be187e1b672a7a1c7c7bae5afdc1ab94a # v3.24.10
      with:
        sarif_file: "trivy-results.sarif"
        token: ${{ inputs.token }}
