name: "Docker Scan and SBOM"
description: "Scan docker containers and generate SBOM"

inputs:
  docker_image:
    description: "The docker image and tag to be scanned"
    required: true
  sbom_name:
    description: "SBOM identification"
    required: true
  token:
    description: "Token for allowing the action to post in the security tab"
    required: true
  upload_docker_vulns:
    description: "Flag to specify vulnerabilities upload"
    required: false
    default: true

env:
  upload_sbom: true

runs:
  using: "composite"
  steps:
    - name: Set upload_sbom variable
      run: |
        echo "upload_sbom=${{ github.event_name == 'push' && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}" >> $GITHUB_ENV
      shell: bash

    - name: Re-tag docker image
      run: |
        docker tag ${{ inputs.docker_image }} ${{ inputs.sbom_name }}
      shell: bash

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.34.0
      shell: bash

    - name: run trivy docker
      if: env.upload_sbom == 'true'
      run: |
        trivy image \
          --format github \
          --vuln-type os,library \
          --security-checks vuln \
          --output dependency-results.sbom.json \
          ${{ inputs.sbom_name }}
      shell: bash

    - name: replace apk with alpine
      if: env.upload_sbom == 'true'
      run: |
        sed -i 's/pkg:apk/pkg:alpine/g' dependency-results.sbom.json
      shell: bash

    - name: replace correlator
      if: env.upload_sbom == 'true'
      run: |
        cat dependency-results.sbom.json | jq '.job.correlator = "${{ inputs.sbom_name }}"' > sbom.tmp 
        mv sbom.tmp dependency-results.sbom.json
      shell: bash

    - name: add mask to token
      if: env.upload_sbom == 'true'
      run: |
        echo "::add-mask::${{ inputs.token }}"
      shell: bash
    
    - name: upload sbom to github
      if: env.upload_sbom == 'true'
      run: |
        curl \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: token ${{ inputs.token }}' \
          'https://api.github.com/repos/'$GITHUB_REPOSITORY'/dependency-graph/snapshots' \
          -d @dependency-results.sbom.json
      shell: bash

    - name: run docker vulnerability scanner
      uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5
      if: inputs.upload_docker_vulns == 'true'
      with:
        image-ref: '${{ inputs.sbom_name }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: upload trivy scan results to github security tab
      if: inputs.upload_docker_vulns == 'true'
      uses: github/codeql-action/upload-sarif@b2a92eb56d8cb930006a1c6ed86b0782dd8a4297 # v2.1.35
      with:
        sarif_file: 'trivy-results.sarif'
        token: ${{ inputs.token }}