name: "Docker vulnerability scan"
description: "Scan docker containers for vulnerabilities"

inputs:
  docker_image:
    description: "The docker image and tag to be scanned"
    required: true
  dockerfile_path:
    description: "The path to the Dockerfile being scanned"
    required: true
  token:
    description: "Token for allowing the action to post in the security tab"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run docker vulnerability scanner
      uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54
      with:
        image-ref: "${{ inputs.docker_image }}"
        format: "sarif"
        security-checks: "vuln"
        timeout: "15m"
        output: "trivy-results.sarif"

    - name: Update sarif vulnerability locations
      run: |
        cat trivy-results.sarif | \
          jq '.runs[].results[].locations[].physicalLocation.artifactLocation += {"uri": "${{ inputs.dockerfile_path }}","uriBaseId": "ROOTPATH"}' | \
          jq '.runs[].results[].locations[].physicalLocation.region += {"startLine": 1,"startColumn": 1,"endLine": 1,"endColumn": 1}' > sarif.tmp
        mv sarif.tmp trivy-results.sarif
      shell: bash

    - name: Upload trivy scan results to github security tab
      uses: github/codeql-action/upload-sarif@004c5de30b6423267685b897a3d595e944f7fed5 # v2.20.2
      with:
        sarif_file: "trivy-results.sarif"
        token: ${{ inputs.token }}
