kind: source
spec:
  # Source spec section
  name: aws
  path: cloudquery/aws
  version: "v15.4.0"
  tables: ["*"]
  destinations: ["postgresql"]
  spec: 
  #   # AWS Spec section described below
    regions: 
      - ca-central-1
      - us-east-1
      - us-west-2
    org: # use org to fetch all accounts in the organization
      member_role_name: secopsAssetInventorySecurityAuditRole
      organization_units:
      - ou-5gsq-qhvjdryl
      admin_account:
        role_arn: arn:aws:iam::794722365809:role/ListAccountsInOrg
---
kind: destination
spec:
  name: "postgresql"
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v3.0.0"
  spec:
    connection_string: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"