kind: source
spec:
  # Source spec section
  name: aws
  path: cloudquery/aws
  version: "v15.4.0"
  tables: ["*"]
  destinations: ["postgresql"]
  spec: 
  #   # AWS Spec section described below
    regions: 
      - ca-central-1
      - us-east-1
      - us-west-2
    # accounts: # use accounts to fetch specific accounts
    #   - id: cds-guillaume-charest-test-132761243856
    #     role_arn: arn:aws:iam::274536870005:role/secopsAssetInventorySecurityAuditRole
    org: # use org to fetch all accounts in the organization
      member_role_name: secopsAssetInventorySecurityAuditRole
      organization_units:
      - ou-5gsq-qhvjdryl
---
kind: destination
spec:
  name: "postgresql"
  registry: "github"
  path: "cloudquery/postgresql"
  version: "v3.0.0"
  spec:
    connection_string: "postgres://postgres:password@host.docker.internal:5432/postgres?sslmode=disable"