# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "security-tools-794722365809-tfstate"
    dynamodb_table = "tfstate-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ca-central-1"
  }
}
