# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "security-tools-794722365809-tfstate"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ca-central-1"
    use_lockfile   = true
  }
}
