name: "Generate ITSG-33 control GitHub issues"
description: "Create github issues for each controls provided in the csv file"

inputs:
  token:
    description: "Token for allowing the action to create issues"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: cds-snc/security-tools
        path: ./.github/tmp/security-tools
      
    - name: Run python script to create gh issues
      working-directory: ./.github/tmp/security-tools/tools/itsg33-issue-generator
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO: ${{ github.repository }}
      run: |
        make install
        make
      shell: bash