kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v25.5.0"
  tables: ["*"]
  skip_tables:
  - aws_ec2_vpc_endpoint_services # this resource includes services that are available from AWS as well as other AWS Accounts
  - aws_cloudtrail_events
  - aws_docdb_cluster_parameter_groups
  - aws_docdb_engine_versions
  - aws_ec2_instance_types
  - aws_elasticache_engine_versions
  - aws_elasticache_parameter_groups
  - aws_elasticache_reserved_cache_nodes_offerings
  - aws_elasticache_service_updates
  - aws_iam_group_last_accessed_details
  - aws_iam_policy_last_accessed_details
  - aws_iam_role_last_accessed_details
  - aws_iam_user_last_accessed_details
  - aws_neptune_cluster_parameter_groups
  - aws_neptune_db_parameter_groups
  - aws_rds_cluster_parameter_groups
  - aws_rds_db_parameter_groups
  - aws_rds_engine_versions
  - aws_servicequotas_services
  destinations: ["sqlite"]
  spec:
    regions:
      - ca-central-1
      - us-east-1
      - us-west-2
    org:
      member_role_name: secopsAssetInventorySecurityAuditRole
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  registry: cloudquery
  version: "v2.7.6"
  spec:
    connection_string: sqlite:////workspace/db.sqlite3