services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CLOUDQUERY_API_KEY: ${CLOUDQUERY_API_KEY}
    volumes:
      - ../..:/workspaces:cached
      - logs:/var/log
    command: sleep infinity
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    cap_add:
      - NET_ADMIN
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
volumes:
  postgres-data:
  logs:
