name: "Generate Docker SBOM"
description: "Generates a Docker SBOM and uploads it to GitHub's asset inventory"

inputs:
  docker_image:
    description: "The Docker image and tag used to generate the SBOM"
    required: true
  dockerfile_path:
    description: "The path to the Dockerfile being scanned"
    required: true
  platform:
    description: "The Docker image platform that's being scanned"
    required: false
    default: "linux/amd64"
  sbom_name:
    description: "The name of the SBOM"
    required: true
  token:
    description: "Token for allowing the action to post in the security tab"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Trivy
      env:
        TRIVY_VERSION: "v0.36.0"
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | \
          sh -s -- -b /usr/local/bin ${{ env.TRIVY_VERSION }}
      shell: bash

    - name: Re-tag docker image
      run: |
        docker pull ${{ inputs.docker_image }} --platform ${{ inputs.platform }}
        docker tag ${{ inputs.docker_image }} ${{ inputs.sbom_name }}
      shell: bash

    - name: Trivy scan
      run: |
        trivy image \
          --format github \
          --platform ${{ inputs.platform }} \
          --vuln-type os,library \
          --security-checks vuln \
          --timeout 15m \
          --output dependency-results.sbom.json \
          ${{ inputs.sbom_name }}
      shell: bash

    - name: SBOM fix - update apk package type to alpine
      run: |
        sed -i 's/pkg:apk/pkg:alpine/g' dependency-results.sbom.json
      shell: bash

    - name: SBOM fix - group scans with correlator and set Dockerfile path
      run: |
        cat dependency-results.sbom.json | \
          jq '.job.correlator = "${{ inputs.sbom_name }}"' | \
          jq '.manifests[] += {"file":{"source_location": "${{ inputs.dockerfile_path }}"}}' > sbom.tmp
        mv sbom.tmp dependency-results.sbom.json
      shell: bash

    - name: Upload SBOM
      run: |
        curl \
          -H 'Accept: application/vnd.github+json' \
          -H 'Authorization: token ${{ inputs.token }}' \
          'https://api.github.com/repos/'$GITHUB_REPOSITORY'/dependency-graph/snapshots' \
          -d @dependency-results.sbom.json
      shell: bash
