name: Source code security scan using Bandit
on:
  pull_request:
    paths:
      - "**/*.py"

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Bandit
      run: |
        .github/workflows/scripts/run_bandit_scan.sh



