name: "Terragrunt plan cloud asset inventory"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/cloud-asset-inventory-terragrunt-plan.yml"
      - "terragrunt/*/cloud_asset_inventory/**"
      - "terragrunt/*/common/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.27.0
  TERRAFORM_VERSION: 1.1.9
  TERRAGRUNT_VERSION: 0.36.7
  TF_INPUT: false

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - uses: cds-snc/paths-filter@v2.10.3
        id: filter
        with:
          filters: |
            cloud_asset_inventory:
              - 'terragrunt/aws/cloud_asset_inventory/**'
              - 'terragrunt/env/cloud_asset_inventory/**'
            common:
              - '.github/workflows/cloud-asset-inventory-terragrunt-plan.yml'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/gh_plan_role
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Get current date to determine if secrets need to be rotated
        run: echo "TF_VAR_password_change_id=$(date +'%Y-%m')" >> $GITHUB_ENV

      - name: Terragrunt plan cloud_asset_inventory
        if: ${{ steps.filter.outputs.cloud_asset_inventory == 'true' || steps.filter.outputs.common == 'true' }}
        uses: cds-snc/terraform-plan@v2
        with:
          directory: "terragrunt/env/cloud_asset_inventory"
          comment-delete: "true"
          comment-title: "cloud_asset_inventory"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"
