name: JSON lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.json"
      - "**/*.json.tmpl"
      - ".github/workflows/json-lint.yml"
  push:
    branches:
      - main
    paths:
      - "**/*.json"
      - "**/*.json.tmpl"
      - ".github/workflows/json-lint.yml"

jobs:
  json-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Lint JSON
        run: find . -name "*.json" -exec cat {} \; | jq .

      - name: Lint JSON templates
        run: find . -name "*.json.tmpl" -exec cat {} \; | sed "s/\${[^}]*}//g" | jq . # remove ${} placeholders
