name: "Terragrunt apply sso proxy"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sso-proxy-terragrunt-apply.yml"
      - "terragrunt/*/sso_proxy/**"
      - "terragrunt/*/common/**"
      - "terragrunt/env/terragrunt.hcl"

env:
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.27.0
  TERRAFORM_VERSION: 1.15.5
  TERRAGRUNT_VERSION: 1.0.6
  TF_INPUT: false
  TF_VAR_pomerium_client_id: ${{ secrets.POMERIUM_CLIENT_ID }}
  TF_VAR_pomerium_client_secret: ${{ secrets.POMERIUM_CLIENT_SECRET }}
  TF_VAR_pomerium_google_client_id: ${{ secrets.POMERIUM_GOOGLE_CLIENT_ID }}
  TF_VAR_pomerium_google_client_secret: ${{ secrets.POMERIUM_GOOGLE_CLIENT_SECRET }}
  TF_VAR_session_cookie_secret: ${{ secrets.SESSION_COOKIE_SECRET }}
  TF_VAR_session_key: ${{ secrets.SESSION_KEY }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@36df0d7572a15921998170395475093c183d720a # v1.3.0

      - uses: cds-snc/paths-filter@b316143212d841aed668b7b29240c719d603a9b9 # v2.10.4
        id: filter
        with:
          filters: |
            sso_proxy:
              - 'terragrunt/aws/sso_proxy/**'
              - 'terragrunt/env/sso_proxy/**'
            common:
              - '.github/workflows/sso-proxy-terragrunt-apply.yml'
              - 'terragrunt/env/common/**'
              - 'terragrunt/env/terragrunt.hcl'

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@ffc08eae7350b1061d7de219e2135c75561fb680 # master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/security-tools-apply
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt apply sso proxy
        if: ${{ steps.filter.outputs.sso_proxy == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: "terragrunt/env/sso_proxy"
        run: terragrunt run --non-interactive -- apply -auto-approve
